
public class Dashboard_Distributor_Frame extends javax.swing.JFrame {

    private static int distributorID;
    public Dashboard_Distributor_Frame(int distributorID) {
        this.distributorID = distributorID;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_Logout = new javax.swing.JButton();
        btn_Purchase_Orders_ = new javax.swing.JButton();
        btn_Invoices_ = new javax.swing.JButton();
        btn_Medicines_List_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hello Distributors!");

        btn_Logout.setText("Logout");
        btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogoutActionPerformed(evt);
            }
        });

        btn_Purchase_Orders_.setText("Purchase Orders");
        btn_Purchase_Orders_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Purchase_Orders_ActionPerformed(evt);
            }
        });

        btn_Invoices_.setText("Invoices");
        btn_Invoices_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Invoices_ActionPerformed(evt);
            }
        });

        btn_Medicines_List_.setText("Medicines List");
        btn_Medicines_List_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Medicines_List_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Logout)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Purchase_Orders_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Invoices_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Medicines_List_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Logout)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addComponent(btn_Medicines_List_)
                .addGap(18, 18, 18)
                .addComponent(btn_Purchase_Orders_)
                .addGap(18, 18, 18)
                .addComponent(btn_Invoices_)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoutActionPerformed
        Login_Frame login = new Login_Frame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_LogoutActionPerformed

    private void btn_Purchase_Orders_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Purchase_Orders_ActionPerformed
        Purchase_Orders_Frame purchase_orders = new Purchase_Orders_Frame(distributorID);
        purchase_orders.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_Purchase_Orders_ActionPerformed

    private void btn_Medicines_List_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Medicines_List_ActionPerformed
        View_Medicines_Frame view_medicines = new View_Medicines_Frame(distributorID);
        view_medicines.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_Medicines_List_ActionPerformed

    private void btn_Invoices_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Invoices_ActionPerformed
        Invoices_Frame invoices = new Invoices_Frame();
        invoices.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_Invoices_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Distributor_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Distributor_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Distributor_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Distributor_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_Distributor_Frame(distributorID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Invoices_;
    private javax.swing.JButton btn_Logout;
    private javax.swing.JButton btn_Medicines_List_;
    private javax.swing.JButton btn_Purchase_Orders_;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
