public class Dashboard_Frame extends javax.swing.JFrame {

    private static int empID; 
    public Dashboard_Frame(int empID) {
        this.empID = empID;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_Production_Lines_ = new javax.swing.JButton();
        btn_Employees_ = new javax.swing.JButton();
        btn_Medicines_ = new javax.swing.JButton();
        btn_Distributors_ = new javax.swing.JButton();
        btn_Purchase_Orders_ = new javax.swing.JButton();
        btn_Invoices_ = new javax.swing.JButton();
        btn_Logout_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dashboard Manager!");

        btn_Production_Lines_.setText(" Production Lines Management");
        btn_Production_Lines_.setActionCommand("Production Lines Management");
        btn_Production_Lines_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Production_Lines_ActionPerformed(evt);
            }
        });

        btn_Employees_.setText("Employees Management");
        btn_Employees_.setMaximumSize(new java.awt.Dimension(194, 23));
        btn_Employees_.setMinimumSize(new java.awt.Dimension(194, 23));
        btn_Employees_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Employees_ActionPerformed(evt);
            }
        });

        btn_Medicines_.setText("Medicines Details");
        btn_Medicines_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Medicines_ActionPerformed(evt);
            }
        });

        btn_Distributors_.setText("Distributors");
        btn_Distributors_.setActionCommand("Distributors");
        btn_Distributors_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Distributors_ActionPerformed(evt);
            }
        });

        btn_Purchase_Orders_.setText("Purchase Orders");
        btn_Purchase_Orders_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Purchase_Orders_ActionPerformed(evt);
            }
        });

        btn_Invoices_.setText("Invoices");
        btn_Invoices_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Invoices_ActionPerformed(evt);
            }
        });

        btn_Logout_.setText("logout");
        btn_Logout_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Logout_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Employees_, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Production_Lines_)
                    .addComponent(btn_Medicines_, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Distributors_, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Purchase_Orders_, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Invoices_, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Logout_)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Logout_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Production_Lines_)
                .addGap(18, 18, 18)
                .addComponent(btn_Employees_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Medicines_)
                .addGap(18, 18, 18)
                .addComponent(btn_Distributors_)
                .addGap(18, 18, 18)
                .addComponent(btn_Purchase_Orders_)
                .addGap(18, 18, 18)
                .addComponent(btn_Invoices_)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Production_Lines_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Production_Lines_ActionPerformed
        Lines_Frame lines = new Lines_Frame(empID);
        lines.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_Production_Lines_ActionPerformed

    private void btn_Employees_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Employees_ActionPerformed
        Employees_Frame emp_frame = new Employees_Frame(empID);
        emp_frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_Employees_ActionPerformed

    private void btn_Medicines_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Medicines_ActionPerformed
        Medicines_Frame medicines = new Medicines_Frame(empID);
        medicines.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_Medicines_ActionPerformed

    private void btn_Logout_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Logout_ActionPerformed
       Login_Frame login = new Login_Frame();
       login.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_Logout_ActionPerformed

    private void btn_Purchase_Orders_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Purchase_Orders_ActionPerformed
        View_Purchase_Orders_Frame view_purchase = new View_Purchase_Orders_Frame();
        view_purchase.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_Purchase_Orders_ActionPerformed

    private void btn_Distributors_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Distributors_ActionPerformed
        Distributors_Frame distributors = new Distributors_Frame(empID);
        distributors.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_Distributors_ActionPerformed

    private void btn_Invoices_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Invoices_ActionPerformed
        Invoices_Frame invoices = new Invoices_Frame();
        invoices.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_Invoices_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_Frame(empID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Distributors_;
    private javax.swing.JButton btn_Employees_;
    private javax.swing.JButton btn_Invoices_;
    private javax.swing.JButton btn_Logout_;
    private javax.swing.JButton btn_Medicines_;
    private javax.swing.JButton btn_Production_Lines_;
    private javax.swing.JButton btn_Purchase_Orders_;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
