import Pharma_Production.DatabaseUtil;
import javax.swing.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.util.Date;


public class Manufacturing_Frame extends javax.swing.JFrame {

    private static int empID; 
    private static int lineId;
    public Manufacturing_Frame(int lineId, int empID) {
        this.lineId = lineId;
        this.empID = empID;
        initComponents();
        lbl_Line_Id.setText("Line ID: " + lineId);
        loadTradeNames(lineId);
    }
    
   private void loadTradeNames(int lineId) {
        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            conn = DatabaseUtil.getConnection();
            String sql = "SELECT TradeName FROM Medicines WHERE LineID = ?";
            pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, lineId);
            rs = pstmt.executeQuery();

            List<String> tradeNames = new ArrayList<>();
            while (rs.next()) {
                String tradeName = rs.getString("TradeName");
                System.out.println("Retrieved TradeName: " + tradeName); // Debugging output
                tradeNames.add(tradeName);
            }

            if (tradeNames.isEmpty()) {
                System.out.println("No trade names found for LineID: " + this.lineId); // Debugging output
            }

            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(tradeNames.toArray(new String[0]));
            cmb_Trade_Name.setModel(model);

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading trade names from database.");
        } finally {
            DatabaseUtil.close(conn, pstmt, rs);
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Back_ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        cmb_Trade_Name = new javax.swing.JComboBox<>();
        date_Expir = new com.toedter.calendar.JCalendar();
        txt_Quantity = new javax.swing.JTextField();
        btn_Manufacturing_ = new javax.swing.JButton();
        lbl_Line_Id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Back_.setText("Back");
        btn_Back_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Back_ActionPerformed(evt);
            }
        });

        jLabel1.setText("Trade Name ");

        jLabel3.setText("Expiration Date ");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jLabel2.setText("Quantity");

        btn_Manufacturing_.setBackground(new java.awt.Color(153, 153, 255));
        btn_Manufacturing_.setText("Manufacturing");
        btn_Manufacturing_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Manufacturing_ActionPerformed(evt);
            }
        });

        lbl_Line_Id.setBackground(new java.awt.Color(204, 204, 255));
        lbl_Line_Id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Line_Id.setText("Line:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(btn_Manufacturing_)))
                    .addComponent(btn_Back_))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(date_Expir, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_Trade_Name, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_Quantity))
                    .addComponent(lbl_Line_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Back_)
                    .addComponent(lbl_Line_Id))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmb_Trade_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txt_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(53, 53, 53)
                        .addComponent(btn_Manufacturing_))
                    .addComponent(date_Expir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Back_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Back_ActionPerformed
        Lines_Frame lines = new Lines_Frame(empID);
        lines.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_Back_ActionPerformed

    private void btn_Manufacturing_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Manufacturing_ActionPerformed
        Connection conn = null;
        PreparedStatement pstmtInsert = null;
        PreparedStatement pstmtUpdate = null;
        ResultSet rs = null;

        try {
            // Validate Expiration Date
            java.util.Date selectedDate = date_Expir.getDate();
            if (selectedDate != null) {
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String formattedDate = dateFormat.format(selectedDate);
                System.out.println("Selected Expiration Date: " + formattedDate);
            } else {
                System.out.println("No date selected");
            }
            /*
            java.sql.Date currentDate = new java.sql.Date(System.currentTimeMillis());
            if (selectedDate.before(currentDate)) {
                JOptionPane.showMessageDialog(this, "Expiration Date cannot be earlier than the current date.");
                return;
            }*/

            // Retrieve selected TradeName and Quantity
            String tradeName = (String) cmb_Trade_Name.getSelectedItem();
            int quantity = Integer.parseInt(txt_Quantity.getText());

            conn = DatabaseUtil.getConnection();
            conn.setAutoCommit(false); // Start transaction

            // Get MedicineID for the selected TradeName
            String sqlSelect = "SELECT MedicineID FROM Medicines WHERE TradeName = ? AND LineID = ?";
            pstmtInsert = conn.prepareStatement(sqlSelect);
            pstmtInsert.setString(1, tradeName);
            pstmtInsert.setInt(2, this.lineId);
            rs = pstmtInsert.executeQuery();

            if (rs.next()) {
                int medicineId = rs.getInt("MedicineID");

                // Insert into ManufacturingDetails
                String sqlInsert = "INSERT INTO ManufacturingDetails (MedicineID, ManufacturingDate, ExpirationDate, Quantity) VALUES (?, ?, ?, ?)";
                pstmtInsert = conn.prepareStatement(sqlInsert);
                pstmtInsert.setInt(1, medicineId);
                pstmtInsert.setDate(2, new java.sql.Date(System.currentTimeMillis())); // Use current date for ManufacturingDate
                pstmtInsert.setDate(3, new java.sql.Date(selectedDate.getTime()));
                pstmtInsert.setInt(4, quantity);
                pstmtInsert.executeUpdate();

                // Update TotalQuantity in Medicines
                String sqlUpdate = "UPDATE Medicines SET TotalQuantity = TotalQuantity + ? WHERE MedicineID = ?";
                pstmtUpdate = conn.prepareStatement(sqlUpdate);
                pstmtUpdate.setInt(1, quantity);
                pstmtUpdate.setInt(2, medicineId);
                pstmtUpdate.executeUpdate();

                conn.commit(); // Commit transaction
                JOptionPane.showMessageDialog(this, "Manufacturing details added successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Selected trade name not found for the given line ID.");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            try {
                if (conn != null) conn.rollback(); // Rollback transaction in case of error
            } catch (SQLException e) {
                e.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Error during manufacturing process.");
        } finally {
            DatabaseUtil.close(conn, pstmtInsert, rs);
            DatabaseUtil.close(conn, pstmtUpdate);
        }
    }//GEN-LAST:event_btn_Manufacturing_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manufacturing_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manufacturing_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manufacturing_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manufacturing_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manufacturing_Frame(lineId, empID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back_;
    private javax.swing.JButton btn_Manufacturing_;
    private javax.swing.JComboBox<String> cmb_Trade_Name;
    private com.toedter.calendar.JCalendar date_Expir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lbl_Line_Id;
    private javax.swing.JTextField txt_Quantity;
    // End of variables declaration//GEN-END:variables
}
