
public class Medicines_Frame extends javax.swing.JFrame {

    private static int empID; 
    public Medicines_Frame(int empID) {
        this.empID = empID;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Add_Medicine_ = new javax.swing.JButton();
        btn_View_Medicines_ = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_BestSellingMedications2024 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Add_Medicine_.setText("Add Medicine");
        btn_Add_Medicine_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add_Medicine_ActionPerformed(evt);
            }
        });

        btn_View_Medicines_.setText("View Medicines");
        btn_View_Medicines_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_View_Medicines_ActionPerformed(evt);
            }
        });

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_BestSellingMedications2024.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_BestSellingMedications2024.setForeground(new java.awt.Color(102, 102, 255));
        btn_BestSellingMedications2024.setText("BestSellingMedications2024");
        btn_BestSellingMedications2024.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BestSellingMedications2024ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_back))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_BestSellingMedications2024, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_View_Medicines_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Add_Medicine_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_back)
                .addGap(43, 43, 43)
                .addComponent(btn_Add_Medicine_)
                .addGap(42, 42, 42)
                .addComponent(btn_View_Medicines_)
                .addGap(36, 36, 36)
                .addComponent(btn_BestSellingMedications2024)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Add_Medicine_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add_Medicine_ActionPerformed
        Add_Medicine_Frame add_medicine = new Add_Medicine_Frame(empID);
        add_medicine.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_Add_Medicine_ActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        Dashboard_Frame dashboard = new Dashboard_Frame(empID);
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_View_Medicines_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_View_Medicines_ActionPerformed
        View_Medicines_Frame view_medicines = new View_Medicines_Frame(empID);
        view_medicines.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_View_Medicines_ActionPerformed

    private void btn_BestSellingMedications2024ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BestSellingMedications2024ActionPerformed
        BestSellingMedications2024_Frame BestSellingMedications2024 = new BestSellingMedications2024_Frame();
        BestSellingMedications2024.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_BestSellingMedications2024ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medicines_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medicines_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medicines_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medicines_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medicines_Frame(empID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add_Medicine_;
    private javax.swing.JButton btn_BestSellingMedications2024;
    private javax.swing.JButton btn_View_Medicines_;
    private javax.swing.JButton btn_back;
    // End of variables declaration//GEN-END:variables
}
